### ISSUE TITLE
Implement lab8/activity_selection_problem

### ISSUE THREAD

**Issue by sanatsingh** [arindas/CS-2008#10]

**Comment by AbhishAnand** [comment]
#include<stdio.h>
void swap(int *x,int *y)
{
    *x = *x + *y; 
    *y = *x - *y;
    *x = *x - *y;
	
}
int main()
{
	int s[10],f[10],i,j,n,a[10],k=0;
	printf("Enter no of activity\n");
	scanf("%d",&n);
	printf("Enter start and finish time\n");
	for(i=0;i<n;i++)
	{
      a[i]=i+1;
	  printf("A[%d]",a[i]);	
	  scanf("%d%d",&s[i],&f[i]);
    }
	for(i=0;i<n;i++)
	{
		for(j=0;j<n-i-1;j++)
		{
			if(f[j]>f[j+1])
			{
			swap(&f[j],&f[j+1]);
			swap(&s[j],&s[j+1]);
		    }
		}
	}
	printf("The Activities are: \n");
	printf("A[%d]",a[0]);
	for(i=0;i<n;i++)
	{
		if(s[i]>=f[k])
		{
			printf("A[%d]",a[i]);
			k=i;
		}
	}
	return 0;
}
